// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: github.com/buildbarn/bb-action-router/pkg/proto/configuration/docker_root_fetcher/docker_root_fetcher.proto

package docker_root_fetcher

import (
	build_user "github.com/buildbarn/bb-action-router/pkg/proto/configuration/build_user"
	registry_auth "github.com/buildbarn/bb-action-router/pkg/proto/configuration/registry_auth"
	blobstore "github.com/buildbarn/bb-storage/pkg/proto/configuration/blobstore"
	global "github.com/buildbarn/bb-storage/pkg/proto/configuration/global"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationConfiguration struct {
	state                    protoimpl.MessageState                               `protogen:"open.v1"`
	Global                   *global.Configuration                                `protobuf:"bytes,1,opt,name=global,proto3" json:"global,omitempty"`
	SocketPath               string                                               `protobuf:"bytes,2,opt,name=socket_path,json=socketPath,proto3" json:"socket_path,omitempty"`
	FetchParallelism         uint32                                               `protobuf:"varint,8,opt,name=fetch_parallelism,json=fetchParallelism,proto3" json:"fetch_parallelism,omitempty"`
	FetchOpenDirectoryLimit  uint32                                               `protobuf:"varint,9,opt,name=fetch_open_directory_limit,json=fetchOpenDirectoryLimit,proto3" json:"fetch_open_directory_limit,omitempty"`
	RootsDirectoryPath       string                                               `protobuf:"bytes,10,opt,name=roots_directory_path,json=rootsDirectoryPath,proto3" json:"roots_directory_path,omitempty"`
	MaximumMaterializedRoots int32                                                `protobuf:"varint,11,opt,name=maximum_materialized_roots,json=maximumMaterializedRoots,proto3" json:"maximum_materialized_roots,omitempty"`
	MaximumMessageSizeBytes  int32                                                `protobuf:"varint,12,opt,name=maximum_message_size_bytes,json=maximumMessageSizeBytes,proto3" json:"maximum_message_size_bytes,omitempty"`
	RegistryAuthentication   []*registry_auth.RegistryAuthenticationConfiguration `protobuf:"bytes,14,rep,name=registry_authentication,json=registryAuthentication,proto3" json:"registry_authentication,omitempty"`
	MaximumImageSizeBytes    int64                                                `protobuf:"varint,15,opt,name=maximum_image_size_bytes,json=maximumImageSizeBytes,proto3" json:"maximum_image_size_bytes,omitempty"`
	ImagePullTimeout         *durationpb.Duration                                 `protobuf:"bytes,16,opt,name=image_pull_timeout,json=imagePullTimeout,proto3" json:"image_pull_timeout,omitempty"`
	OtlpCollectorEndpoints   []string                                             `protobuf:"bytes,17,rep,name=otlp_collector_endpoints,json=otlpCollectorEndpoints,proto3" json:"otlp_collector_endpoints,omitempty"`
	MaximumConcurrentFetches uint32                                               `protobuf:"varint,18,opt,name=maximum_concurrent_fetches,json=maximumConcurrentFetches,proto3" json:"maximum_concurrent_fetches,omitempty"`
	AcquireTimeout           *durationpb.Duration                                 `protobuf:"bytes,19,opt,name=acquire_timeout,json=acquireTimeout,proto3" json:"acquire_timeout,omitempty"`
	PrefetchImages           []string                                             `protobuf:"bytes,20,rep,name=prefetch_images,json=prefetchImages,proto3" json:"prefetch_images,omitempty"`
	BuildUser                *build_user.BuildUser                                `protobuf:"bytes,21,opt,name=build_user,json=buildUser,proto3" json:"build_user,omitempty"`
	RootUseBoost             *durationpb.Duration                                 `protobuf:"bytes,22,opt,name=root_use_boost,json=rootUseBoost,proto3" json:"root_use_boost,omitempty"`
	MaximumRootUseBoost      *durationpb.Duration                                 `protobuf:"bytes,23,opt,name=maximum_root_use_boost,json=maximumRootUseBoost,proto3" json:"maximum_root_use_boost,omitempty"`
	DependencyBlobstore      *blobstore.BlobstoreConfiguration                    `protobuf:"bytes,24,opt,name=dependency_blobstore,json=dependencyBlobstore,proto3" json:"dependency_blobstore,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ApplicationConfiguration) Reset() {
	*x = ApplicationConfiguration{}
	mi := &file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration) ProtoMessage() {}

func (x *ApplicationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationConfiguration) GetGlobal() *global.Configuration {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *ApplicationConfiguration) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

func (x *ApplicationConfiguration) GetFetchParallelism() uint32 {
	if x != nil {
		return x.FetchParallelism
	}
	return 0
}

func (x *ApplicationConfiguration) GetFetchOpenDirectoryLimit() uint32 {
	if x != nil {
		return x.FetchOpenDirectoryLimit
	}
	return 0
}

func (x *ApplicationConfiguration) GetRootsDirectoryPath() string {
	if x != nil {
		return x.RootsDirectoryPath
	}
	return ""
}

func (x *ApplicationConfiguration) GetMaximumMaterializedRoots() int32 {
	if x != nil {
		return x.MaximumMaterializedRoots
	}
	return 0
}

func (x *ApplicationConfiguration) GetMaximumMessageSizeBytes() int32 {
	if x != nil {
		return x.MaximumMessageSizeBytes
	}
	return 0
}

func (x *ApplicationConfiguration) GetRegistryAuthentication() []*registry_auth.RegistryAuthenticationConfiguration {
	if x != nil {
		return x.RegistryAuthentication
	}
	return nil
}

func (x *ApplicationConfiguration) GetMaximumImageSizeBytes() int64 {
	if x != nil {
		return x.MaximumImageSizeBytes
	}
	return 0
}

func (x *ApplicationConfiguration) GetImagePullTimeout() *durationpb.Duration {
	if x != nil {
		return x.ImagePullTimeout
	}
	return nil
}

func (x *ApplicationConfiguration) GetOtlpCollectorEndpoints() []string {
	if x != nil {
		return x.OtlpCollectorEndpoints
	}
	return nil
}

func (x *ApplicationConfiguration) GetMaximumConcurrentFetches() uint32 {
	if x != nil {
		return x.MaximumConcurrentFetches
	}
	return 0
}

func (x *ApplicationConfiguration) GetAcquireTimeout() *durationpb.Duration {
	if x != nil {
		return x.AcquireTimeout
	}
	return nil
}

func (x *ApplicationConfiguration) GetPrefetchImages() []string {
	if x != nil {
		return x.PrefetchImages
	}
	return nil
}

func (x *ApplicationConfiguration) GetBuildUser() *build_user.BuildUser {
	if x != nil {
		return x.BuildUser
	}
	return nil
}

func (x *ApplicationConfiguration) GetRootUseBoost() *durationpb.Duration {
	if x != nil {
		return x.RootUseBoost
	}
	return nil
}

func (x *ApplicationConfiguration) GetMaximumRootUseBoost() *durationpb.Duration {
	if x != nil {
		return x.MaximumRootUseBoost
	}
	return nil
}

func (x *ApplicationConfiguration) GetDependencyBlobstore() *blobstore.BlobstoreConfiguration {
	if x != nil {
		return x.DependencyBlobstore
	}
	return nil
}

var File_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_rawDesc = "" +
	"\n" +
	"kgithub.com/buildbarn/bb-action-router/pkg/proto/configuration/docker_root_fetcher/docker_root_fetcher.proto\x12+buildbarn.configuration.docker_root_fetcher\x1a\x1egoogle/protobuf/duration.proto\x1aQgithub.com/buildbarn/bb-storage/pkg/proto/configuration/blobstore/blobstore.proto\x1aYgithub.com/buildbarn/bb-action-router/pkg/proto/configuration/build_user/build_user.proto\x1a_github.com/buildbarn/bb-action-router/pkg/proto/configuration/registry_auth/registry_auth.proto\x1aKgithub.com/buildbarn/bb-storage/pkg/proto/configuration/global/global.proto\"\xd3\t\n" +
	"\x18ApplicationConfiguration\x12E\n" +
	"\x06global\x18\x01 \x01(\v2-.buildbarn.configuration.global.ConfigurationR\x06global\x12\x1f\n" +
	"\vsocket_path\x18\x02 \x01(\tR\n" +
	"socketPath\x12+\n" +
	"\x11fetch_parallelism\x18\b \x01(\rR\x10fetchParallelism\x12;\n" +
	"\x1afetch_open_directory_limit\x18\t \x01(\rR\x17fetchOpenDirectoryLimit\x120\n" +
	"\x14roots_directory_path\x18\n" +
	" \x01(\tR\x12rootsDirectoryPath\x12<\n" +
	"\x1amaximum_materialized_roots\x18\v \x01(\x05R\x18maximumMaterializedRoots\x12;\n" +
	"\x1amaximum_message_size_bytes\x18\f \x01(\x05R\x17maximumMessageSizeBytes\x12\x83\x01\n" +
	"\x17registry_authentication\x18\x0e \x03(\v2J.buildbarn.configuration.registry_auth.RegistryAuthenticationConfigurationR\x16registryAuthentication\x127\n" +
	"\x18maximum_image_size_bytes\x18\x0f \x01(\x03R\x15maximumImageSizeBytes\x12G\n" +
	"\x12image_pull_timeout\x18\x10 \x01(\v2\x19.google.protobuf.DurationR\x10imagePullTimeout\x128\n" +
	"\x18otlp_collector_endpoints\x18\x11 \x03(\tR\x16otlpCollectorEndpoints\x12<\n" +
	"\x1amaximum_concurrent_fetches\x18\x12 \x01(\rR\x18maximumConcurrentFetches\x12B\n" +
	"\x0facquire_timeout\x18\x13 \x01(\v2\x19.google.protobuf.DurationR\x0eacquireTimeout\x12'\n" +
	"\x0fprefetch_images\x18\x14 \x03(\tR\x0eprefetchImages\x12L\n" +
	"\n" +
	"build_user\x18\x15 \x01(\v2-.buildbarn.configuration.build_user.BuildUserR\tbuildUser\x12?\n" +
	"\x0eroot_use_boost\x18\x16 \x01(\v2\x19.google.protobuf.DurationR\frootUseBoost\x12N\n" +
	"\x16maximum_root_use_boost\x18\x17 \x01(\v2\x19.google.protobuf.DurationR\x13maximumRootUseBoost\x12l\n" +
	"\x14dependency_blobstore\x18\x18 \x01(\v29.buildbarn.configuration.blobstore.BlobstoreConfigurationR\x13dependencyBlobstoreBSZQgithub.com/buildbarn/bb-action-router/pkg/proto/configuration/docker_root_fetcherb\x06proto3"

var (
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_rawDesc), len(file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_rawDescData
}

var file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_goTypes = []any{
	(*ApplicationConfiguration)(nil),                          // 0: buildbarn.configuration.docker_root_fetcher.ApplicationConfiguration
	(*global.Configuration)(nil),                              // 1: buildbarn.configuration.global.Configuration
	(*registry_auth.RegistryAuthenticationConfiguration)(nil), // 2: buildbarn.configuration.registry_auth.RegistryAuthenticationConfiguration
	(*durationpb.Duration)(nil),                               // 3: google.protobuf.Duration
	(*build_user.BuildUser)(nil),                              // 4: buildbarn.configuration.build_user.BuildUser
	(*blobstore.BlobstoreConfiguration)(nil),                  // 5: buildbarn.configuration.blobstore.BlobstoreConfiguration
}
var file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_depIdxs = []int32{
	1, // 0: buildbarn.configuration.docker_root_fetcher.ApplicationConfiguration.global:type_name -> buildbarn.configuration.global.Configuration
	2, // 1: buildbarn.configuration.docker_root_fetcher.ApplicationConfiguration.registry_authentication:type_name -> buildbarn.configuration.registry_auth.RegistryAuthenticationConfiguration
	3, // 2: buildbarn.configuration.docker_root_fetcher.ApplicationConfiguration.image_pull_timeout:type_name -> google.protobuf.Duration
	3, // 3: buildbarn.configuration.docker_root_fetcher.ApplicationConfiguration.acquire_timeout:type_name -> google.protobuf.Duration
	4, // 4: buildbarn.configuration.docker_root_fetcher.ApplicationConfiguration.build_user:type_name -> buildbarn.configuration.build_user.BuildUser
	3, // 5: buildbarn.configuration.docker_root_fetcher.ApplicationConfiguration.root_use_boost:type_name -> google.protobuf.Duration
	3, // 6: buildbarn.configuration.docker_root_fetcher.ApplicationConfiguration.maximum_root_use_boost:type_name -> google.protobuf.Duration
	5, // 7: buildbarn.configuration.docker_root_fetcher.ApplicationConfiguration.dependency_blobstore:type_name -> buildbarn.configuration.blobstore.BlobstoreConfiguration
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() {
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_init()
}
func file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_init() {
	if File_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_rawDesc), len(file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto = out.File
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_goTypes = nil
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_docker_root_fetcher_docker_root_fetcher_proto_depIdxs = nil
}
