load("@com_github_buildbarn_bb_storage//tools:container.bzl", "container_push_official", "multiarch_go_image")
load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")
load("@rules_img//img:image.bzl", "image_from_binary")
load("@rules_img//img:load.bzl", "image_load")
load("@rules_img//img:push.bzl", "image_push")

go_library(
    name = "bb_docker_root_fetcher_lib",
    srcs = ["main.go"],
    importpath = "github.com/buildbarn/bb-action-router/cmd/bb_docker_root_fetcher",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/actionrouter",
        "//pkg/blobstore",
        "//pkg/docker",
        "//pkg/ephemeralcas",
        "//pkg/fetcher",
        "//pkg/logging",
        "//pkg/proto/configuration/docker_root_fetcher",
        "@bazel_remote_apis//build/bazel/remote/execution/v2:remote_execution_go_proto",
        "@com_github_buildbarn_bb_remote_execution//pkg/builder",
        "@com_github_buildbarn_bb_remote_execution//pkg/cas",
        "@com_github_buildbarn_bb_storage//pkg/blobstore",
        "@com_github_buildbarn_bb_storage//pkg/digest",
        "@com_github_buildbarn_bb_storage//pkg/filesystem",
        "@com_github_buildbarn_bb_storage//pkg/filesystem/path",
        "@com_github_buildbarn_bb_storage//pkg/global",
        "@com_github_buildbarn_bb_storage//pkg/program",
        "@com_github_buildbarn_bb_storage//pkg/util",
        "@com_github_google_go_containerregistry//pkg/name",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel_metric//:metric",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_x_sync//semaphore",
    ],
)

go_binary(
    name = "bb_docker_root_fetcher",
    embed = [":bb_docker_root_fetcher_lib"],
    pure = "on",
    visibility = ["//visibility:public"],
)

go_test(
    name = "bb_docker_root_fetcher_test",
    srcs = ["main_test.go"],
    embed = [":bb_docker_root_fetcher_lib"],
)

multiarch_go_image(
    name = "bb_docker_root_fetcher_container",
    binary = ":bb_docker_root_fetcher",
)

container_push_official(
    name = "bb_docker_root_fetcher_container_push",
    component = "bb-root-fetcher",
    image = ":bb_docker_root_fetcher_container",
)

image_from_binary(
    name = "bb_docker_root_fetcher_image",
    binary = ":bb_docker_root_fetcher",
    include_runfiles = False,
    visibility = ["//visibility:public"],
)

image_push(
    name = "push_bb_docker_root_fetcher",
    image = ":bb_docker_root_fetcher_image",
    registry = "docker.io",
    repository = "buildbarn/bb_root_fetcher",
    tag = "latest",
)

# Produces a "docker save" tarball for `kind load image-archive`.
image_load(
    name = "bb_docker_root_fetcher_image_load",
    image = ":bb_docker_root_fetcher_image",
    tag = "bb_docker_root_fetcher:e2e",
)
