load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "actionrouter",
    srcs = [
        "build_user.go",
        "image_to_cas_uploader.go",
        "op_merge.go",
        "operations.go",
        "pipeline.go",
    ],
    importpath = "github.com/buildbarn/bb-action-router/pkg/actionrouter",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/blobstore",
        "//pkg/docker",
        "//pkg/fetcher",
        "//pkg/proto/configuration/bb_docker_action_router",
        "//pkg/proto/configuration/build_user",
        "@bazel_remote_apis//build/bazel/remote/execution/v2:remote_execution_go_proto",
        "@com_github_buildbarn_bb_remote_execution//pkg/blobstore",
        "@com_github_buildbarn_bb_storage//pkg/blobstore",
        "@com_github_buildbarn_bb_storage//pkg/blobstore/buffer",
        "@com_github_buildbarn_bb_storage//pkg/digest",
        "@com_github_buildbarn_bb_storage//pkg/util",
        "@com_github_patrickmn_go_cache//:go-cache",
        "@com_github_prometheus_client_golang//prometheus",
        "@com_github_prometheus_client_golang//prometheus/promauto",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//proto",
        "@org_golang_x_sync//semaphore",
        "@org_golang_x_sync//singleflight",
    ],
)

go_test(
    name = "actionrouter_test",
    srcs = [
        "build_user_test.go",
        "image_to_cas_uploader_test.go",
        "operations_test.go",
        "pipeline_test.go",
    ],
    embed = [":actionrouter"],
    deps = [
        "//internal/mock",
        "//pkg/blobstore",
        "//pkg/docker",
        "//pkg/proto/configuration/bb_docker_action_router",
        "//pkg/proto/configuration/build_user",
        "@bazel_remote_apis//build/bazel/remote/execution/v2:remote_execution_go_proto",
        "@com_github_buildbarn_bb_storage//pkg/blobstore/buffer",
        "@com_github_buildbarn_bb_storage//pkg/digest",
        "@com_github_golang_mock//gomock",
        "@com_github_google_go_containerregistry//pkg/name",
        "@com_github_google_go_containerregistry//pkg/registry",
        "@com_github_google_go_containerregistry//pkg/v1/random",
        "@com_github_google_go_containerregistry//pkg/v1/remote",
        "@com_github_stretchr_testify//require",
        "@org_golang_google_protobuf//proto",
    ],
)
